import os
import psycopg2
from psycopg2.extras import RealDictCursor
from datetime import datetime, timedelta

DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql://postgres:Jagmit232003@db.drydrnxmfdscyrwfopsd.supabase.co:5432/postgres?sslmode=require"
)

def get_db():
    conn = psycopg2.connect(DATABASE_URL, cursor_factory=RealDictCursor)
    return conn

def init_db():
    try:
        conn = get_db()
        cur  = conn.cursor()
        cur.execute("SELECT COUNT(*) as count FROM jobs")
        count = cur.fetchone()["count"]
        if count == 0:
            _seed_jobs(conn)
        conn.close()
        print("✅ Supabase connected and ready.")
    except Exception as e:
        print(f"❌ Supabase connection error: {e}")
        raise e

def _seed_jobs(conn):
    today = datetime.now()
    def d(offset):
        return (today + timedelta(days=offset)).strftime("%Y-%m-%d")

    jobs = [
        ("Google","Python Developer","Python,Django,SQL,REST","Bangalore",d(1),"10:00 AM - 4:00 PM","18-25 LPA","https://maps.app.goo.gl/googleblr","Google India Pvt. Ltd., 3 RMZ Infinity, Old Madras Rd, Bengaluru 560016","Google LLC is an American multinational technology company known for search, cloud, and AI.","We are looking for a skilled Python Developer to design and build efficient backend services.","Build backend services using Python and Django|Collaborate with frontend engineers|Write clean testable code|Optimize for speed","Bachelor in CS or related|2+ years Python experience|Strong Django and REST knowledge|SQL optimization","Walk-in Registration|Coding Test|Technical Round 1|Technical Round 2|HR"),
        ("Amazon","Backend Engineer","Java,Spring,SQL,Microservices","Hyderabad",d(1),"9:00 AM - 3:00 PM","20-30 LPA","https://maps.app.goo.gl/amazonhyd","Amazon Development Centre, Divyasree Techno Park, Whitefield, Hyderabad 500081","Amazon is a global technology and e-commerce giant and AWS is the world's leading cloud platform.","Build and scale core services powering our e-commerce and cloud platforms.","Design microservices using Java and Spring Boot|Build RESTful APIs|Optimize SQL at scale|Write unit and integration tests","3+ years Java experience|Microservices architecture|Spring Boot and Hibernate|AWS knowledge a plus","Walk-in Registration|Aptitude Test|DSA Round|System Design|HR"),
        ("Microsoft","Frontend Developer","HTML,CSS,JavaScript,React","Pune",d(2),"10:00 AM - 5:00 PM","16-22 LPA","https://maps.app.goo.gl/msftpune","Microsoft India R&D, Embassy TechZone, Rajiv Gandhi Infotech Park, Hinjewadi, Pune 411057","Microsoft develops Windows, Azure, Office and Xbox products used worldwide.","Build responsive accessible user interfaces for Microsoft products.","Build web applications using React|Implement pixel-perfect UI|Optimize performance|Write reusable components","2+ years frontend experience|React JavaScript ES6+ HTML5 CSS3|State management knowledge","Walk-in Registration|UI Assessment|Frontend Coding Challenge|Technical Interview|HR"),
        ("Flipkart","Full Stack Developer","Python,React,SQL,Node","Bangalore",d(2),"9:30 AM - 3:30 PM","14-20 LPA","https://maps.app.goo.gl/flipkartblr","Flipkart, Ozone Manay Tech Park, Garvebhavipalya, Hosur Road, Bangalore 560068","Flipkart is India's leading e-commerce marketplace with 500 million registered users.","Own features end-to-end from database design to frontend components.","Build full-stack features using Python/Node and React|Design SQL schemas|Create RESTful APIs","2-4 years full-stack experience|Python or Node.js proficiency|Strong React|Good SQL knowledge","Walk-in Registration|Online Assessment|Backend Round|Frontend Round|HR"),
        ("Wipro","C++ Developer","C++,DSA,Python,Linux","Noida",d(0),"10:00 AM - 4:00 PM","5-9 LPA","https://maps.app.goo.gl/wipronoida","Wipro Limited, A-125, Sector 2, Noida, Uttar Pradesh 201301","Wipro is a global technology services company with 240,000+ employees.","Work on high-performance systems and low-level C++ components.","Develop high-performance C++ applications|System-level programming|DSA implementation|Debug on Linux","1-3 years C++ experience|Strong DSA|Linux environment","Walk-in Registration|Written Test|Technical Interview|Problem Solving|HR"),
        ("Zomato","Data Analyst","Python,SQL,Excel,PowerBI","Gurgaon",d(4),"11:00 AM - 4:00 PM","10-15 LPA","https://maps.app.goo.gl/zomatogur","Zomato Media Pvt. Ltd., 12th Floor Tower D, DLF Cyber City, Gurugram 122022","Zomato is India's leading food delivery and restaurant discovery platform.","Turn raw data into actionable insights driving business decisions.","Analyse datasets using Python and SQL|Build PowerBI dashboards|Track key metrics|Conduct A/B analysis","1-3 years data analysis|Strong SQL|Python pandas numpy|PowerBI or Tableau","Walk-in Registration|SQL Test|Case Study|Technical Round|HR"),
        ("Swiggy","React Developer","React,HTML,CSS,JavaScript,Redux","Bangalore",d(5),"10:00 AM - 3:00 PM","12-18 LPA","https://maps.app.goo.gl/swiggyblr","Bundl Technologies (Swiggy), Embassy Tech Village, Outer Ring Road, Bellandur, Bangalore 560103","Swiggy is India's leading on-demand delivery platform in 500+ cities.","Build fast scalable web applications serving millions of daily users.","Build React.js applications|Implement UI with Redux|Optimize performance|Write unit tests","2+ years React experience|Strong JavaScript|Redux|HTML5 CSS3","Walk-in Registration|React Coding Challenge|Technical Interview|HR"),
        ("Razorpay","Full Stack Engineer","Python,React,SQL,HTML,Node","Bangalore",d(7),"10:00 AM - 5:00 PM","18-26 LPA","https://maps.app.goo.gl/razorpayblr","Razorpay Software Pvt. Ltd., SJR Cyber, 22 Laskar Hosur Road, Adugodi, Bangalore 560030","Razorpay is India's leading fintech company processing billions in payments.","Build payment infrastructure that powers India's economy.","Build full-stack payment features|Design secure APIs|Work on high-availability systems|Implement security","3+ years full-stack experience|Python or Node.js|React.js proficiency|Security mindset","Walk-in Registration|Technical Screening|Backend Design|Frontend Round|Security|HR"),
        ("Infosys","Java Developer","Java,Spring,SQL,Hibernate","Chennai",d(3),"10:00 AM - 4:00 PM","6-10 LPA","https://maps.app.goo.gl/infosyschennai","Infosys Ltd., Mahindra City, Chengalpattu District, Chennai 603002","Infosys is a global leader in technology services with 340,000+ employees.","Build enterprise Java applications for global clients.","Develop enterprise Java apps using Spring and Hibernate|Design RESTful APIs|Optimize SQL","1-3 years Java experience|Spring Framework and Hibernate|Good SQL","Walk-in Registration|Written Test|Technical Round 1|Technical Round 2|HR"),
        ("TCS","SQL Developer","SQL,Python,Excel,Tableau","Mumbai",d(3),"9:00 AM - 2:00 PM","5-8 LPA","https://maps.app.goo.gl/tcsmumbai","Tata Consultancy Services, TCS House, Raveline Street, Fort, Mumbai 400001","TCS is one of India's largest IT companies with 600,000+ employees.","Design and optimize database schemas and support analytics for enterprise clients.","Write complex SQL queries|Design and optimize schemas|Build ETL pipelines|Create Tableau reports","1-2 years SQL development|Strong SQL skills|Excel proficiency|Tableau experience","Walk-in Registration|SQL Written Test|Technical Interview|Tableau Assessment|HR"),
        ("Ola","Android Developer","Java,Android,SQL,Kotlin","Bangalore",d(5),"9:30 AM - 3:30 PM","10-16 LPA","https://maps.app.goo.gl/olablr","ANI Technologies (Ola), Regent Insignia, 3rd Floor, Sadashivanagar, Bangalore 560080","Ola is India's largest ride-hailing platform in 250+ cities.","Build and maintain Android app serving millions of daily active users.","Develop Android app in Kotlin/Java|Build smooth UI|Integrate REST APIs|Optimize performance","2+ years Android experience|Kotlin and Java proficiency|Android SDK and Jetpack","Walk-in Registration|Android Coding Test|Technical Round|Architecture Discussion|HR"),
        ("Paytm","Backend Developer","Java,Spring,SQL,Python,Redis","Noida",d(6),"10:00 AM - 4:00 PM","12-18 LPA","https://maps.app.goo.gl/paytmnoida","One97 Communications (Paytm), B-121, Sector 5, Noida 201301","Paytm is India's leading digital payments company with 350 million+ users.","Build payment infrastructure serving hundreds of millions of Indians.","Build services using Java Spring Boot|Design payment APIs|Implement Redis caching|Optimize SQL","2-4 years backend experience|Java and Spring Boot|Redis experience|SQL optimization","Walk-in Registration|Technical Screening|Core Java Round|System Design|Security|HR"),
        ("HDFC Bank","Software Engineer","Java,SQL,Python,Spring","Mumbai",d(6),"9:00 AM - 1:00 PM","8-12 LPA","https://maps.app.goo.gl/hdfcmumbai","HDFC Bank Ltd., HDFC Bank House, Senapati Bapat Marg, Lower Parel, Mumbai 400013","HDFC Bank is India's largest private sector bank with 8,000+ branches.","Build banking software solutions used by millions of customers daily.","Develop banking applications using Java and Spring|Build secure APIs|Core banking integration","2+ years Java experience|Spring Framework|Strong SQL|Banking domain preferred","Walk-in Registration|Aptitude Test|Technical Interview|SQL Round|HR"),
        ("PhonePe","Data Engineer","Python,SQL,Spark,Kafka","Bangalore",d(7),"9:30 AM - 3:30 PM","16-24 LPA","https://maps.app.goo.gl/phonepeblr","PhonePe Private Limited, Indiqube Margosa, Outer Ring Road, Bellandur, Bangalore 560103","PhonePe is India's leading fintech with 500 million+ users and billions of UPI transactions.","Build massive data pipelines processing billions of events.","Build large-scale pipelines using Spark|Design Kafka streaming|Write optimized SQL|Monitor data quality","2-4 years data engineering|Strong Python|Apache Spark|Kafka knowledge","Walk-in Registration|Data Engineering Assessment|Spark & Kafka Round|System Design|HR"),
        ("BYJU'S","Frontend Engineer","HTML,CSS,JavaScript,React,TypeScript","Bangalore",d(1),"10:00 AM - 4:00 PM","10-15 LPA","https://maps.app.goo.gl/byjusblr","Think & Learn Pvt. Ltd. (BYJU'S), IBC Knowledge Park, Bannerghatta Main Road, Bangalore 560029","BYJU'S is the world's largest edtech company with 150 million+ students.","Build engaging interactive learning experiences for millions of students.","Build interactive components using React and TypeScript|Implement animations|Ensure accessibility","2+ years frontend experience|React.js and TypeScript|HTML5 and CSS3|Passion for edtech","Walk-in Registration|Frontend Coding Assessment|Technical Round|UI/UX Discussion|HR"),
        ("Freshworks","Python Engineer","Python,Django,SQL,REST,Docker","Chennai",d(2),"9:00 AM - 3:00 PM","12-18 LPA","https://maps.app.goo.gl/freshworkschennai","Freshworks Inc., Olympia Technology Park, 370 Anna Salai, Nandanam, Chennai 600035","Freshworks is a global SaaS company listed on NASDAQ building CRM and helpdesk software.","Build backend services powering our SaaS platform used by 68,000+ businesses.","Build REST APIs using Python and Django|Optimize SQL schemas|Containerize with Docker","2-3 years Python experience|Django and REST framework|SQL skills|Docker experience","Walk-in Registration|Python Coding Test|Technical Round|Docker Discussion|HR"),
        ("Meesho","Java Microservices","Java,Spring,SQL,Docker,Kubernetes","Bangalore",d(3),"10:00 AM - 4:00 PM","14-20 LPA","https://maps.app.goo.gl/meeshoblr","Fashnear Technologies (Meesho), 165/1 7th Cross Road, Domlur Layout, Bangalore 560071","Meesho is India's fastest-growing e-commerce platform with 140 million+ users.","Build microservices architecture powering India's next e-commerce wave.","Design Java Spring Boot microservices|Deploy on Kubernetes|Containerize with Docker","2-4 years Java microservices|Spring Boot|Docker and Kubernetes","Walk-in Registration|Java Test|Technical Round|Kubernetes Round|System Design|HR"),
        ("Nykaa","Web Developer","HTML,CSS,JavaScript,React,Redux","Mumbai",d(4),"11:00 AM - 4:00 PM","8-14 LPA","https://maps.app.goo.gl/nykaamumbai","FSN E-Commerce (Nykaa), 104 Vasan Udyog Bhavan, Sun Mill Compound, Lower Parel, Mumbai 400013","Nykaa is India's leading beauty e-commerce platform with 35 million+ monthly active users.","Build high-performance e-commerce web experience for millions of beauty shoppers.","Build React.js e-commerce app|Implement product pages and checkout|Manage state with Redux","2+ years React.js experience|HTML5 CSS3 JavaScript|Redux|Eye for design","Walk-in Registration|Frontend Assessment|React & Redux Round|E-commerce Discussion|HR"),
        ("Dream11","Backend Developer","Python,Go,SQL,Redis,Kafka","Mumbai",d(5),"10:00 AM - 3:00 PM","16-22 LPA","https://maps.app.goo.gl/dream11mumbai","Dream Sports (Dream11), One World Centre, Tower 1B, Senapati Bapat Marg, Lower Parel, Mumbai 400013","Dream11 is India's largest sports gaming platform with 220 million+ users.","Solve scale problems serving 100M+ concurrent users during IPL.","Build high-performance APIs in Python and Go|Design Kafka processing|Implement Redis caching","3+ years backend experience|Python and/or Go|Redis and Kafka|SQL optimization","Walk-in Registration|DSA Test|Backend Technical Round|Redis & Kafka|Scale Discussion|HR"),
        ("Zerodha","Software Engineer","Python,SQL,JavaScript,React,Linux","Bangalore",d(6),"9:30 AM - 2:30 PM","14-20 LPA","https://maps.app.goo.gl/zerodha","Zerodha Broking Ltd., 153/154 4th Cross, J.P. Nagar 4th Phase, Bangalore 560078","Zerodha is India's largest stockbroker with 10 million+ clients — bootstrapped and profitable.","Build trading infrastructure that millions of investors rely on daily.","Build trading features using Python and React|Optimize SQL for financial data|Work on Linux backend","2-4 years development experience|Strong Python|React.js|SQL expertise|Linux skills","Walk-in Registration|Technical Assessment|Backend Round|Frontend Round|Culture Discussion|Offer"),
    ]

    cur = conn.cursor()
    for job in jobs:
        cur.execute("""
            INSERT INTO jobs (company, role, skills_required, location, date,
                walkin_time, avg_salary, location_url, location_desc,
                company_about, job_description, responsibilities,
                qualifications, interview_steps)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """, job)
    conn.commit()
    cur.close()
    print(f"✅ Seeded {len(jobs)} jobs into Supabase.")